### ISSUE TITLE
How to use a conditional DDPM

### ISSUE THREAD

**Issue by xyf9474** [ML-GSAI/EGSDE#5]
Thanks for your outstanding work and I have a question:If I want to use a pretrained conditional DDPM in cat2dog translation work, how can I modify the code to use it instead of a  DDPM for dog 
for example: maybe dog is class 2 when I train the conditional DDPM and in [guided-diffusion](https://github.com/openai/guided-diffusion) I can modify the file:image_sample.py to choose which class I want to generate.But how to modify the code here to be equal to a DDPM for dog.
Looking forward to your reply at your earliest convenience.

**Comment by xyf9474** [comment]
Another question: if I hope to train both cat2dog and dag2cat translation , if I need to train two classifier for cat2dog and dag2cat using run_train_dse.py respectively?

**Comment by gracezhao1997** [comment]
Hi,
For Q1: If you want to use a pretrained conditional DDPM, you can modify the output of noise prediction network (functions.denoising.egsde_sample, line 42-46). Here, you can change the model_output to the output of conditional DDPM.
For Q2: if you hope to train both cat2dog and dag2cat translation , one classifier is enough. In addition, we also perform multi-domain translation. For example, if you want to perform multi-domain image translation in cat, dog and wild, you just need to train a conditional ddpm on 3 classes and a 3-class classifier using run_train_dse.py. Based on that, if you want to perform cat-to-wild, you just need to given the wild class label in conditional ddpm and use the pretrained 3-class classifier.

**Comment by xyf9474** [comment]
Thanks so much for your reply! and I will try it😃
